-- KADOSYS Igrejas - Migracao 060
-- RODAR NO BANCO DE CADA IGREJA (nao e no banco central)
--
-- Modulo KADOSYS Kids: adiciona o campo "explicacao" em cada pergunta
-- dos 11 quizzes oficiais - um ensinamento biblico curto mostrado
-- depois de cada resposta (certa ou errada), pra unir diversao com
-- aprendizado de verdade (ver kids/show.php).

-- Gerado por gerar_migration_060.php - nao editar a mao.

UPDATE kids_conteudos SET quiz_perguntas = '[{"pergunta":"Quem construiu a arca?","alternativas":["Moisés","Noé","Davi","Abraão"],"correta":1,"explicacao":"Foi Noé! Deus pediu que ele construísse uma arca bem grande pra salvar sua família e os animais da grande enchente. Noé obedeceu, mesmo sem entender tudo - e Deus cumpriu a promessa de proteger quem confia nele."},{"pergunta":"Quantos dias e noites choveu no dilúvio?","alternativas":["7","40","100","3"],"correta":1,"explicacao":"Choveu 40 dias e 40 noites! Mesmo com tanta chuva, Noé e sua família ficaram seguros dentro da arca, porque confiaram no plano de Deus."},{"pergunta":"Quem derrotou o gigante Golias?","alternativas":["Saul","Salomão","Davi","Sansão"],"correta":2,"explicacao":"Foi Davi, ainda um jovem pastor! Com uma pedrinha, uma funda e muita fé em Deus, ele venceu um gigante guerreiro. Deus pode usar quem parece pequeno pra fazer coisas grandes."}]'
WHERE origem = 'kadosys' AND tipo = 'quiz' AND titulo = 'Quiz: Personagens da Bíblia';

UPDATE kids_conteudos SET quiz_perguntas = '[{"pergunta":"Qual é o primeiro livro da Bíblia?","alternativas":["Êxodo","Gênesis","Salmos","Mateus"],"correta":1,"explicacao":"É Gênesis! Esse livro conta o começo de tudo: a criação do mundo, do primeiro homem e da primeira mulher, feitos por Deus com muito amor."},{"pergunta":"Quantos livros tem o Novo Testamento?","alternativas":["27","39","66","12"],"correta":0,"explicacao":"São 27 livros! Eles contam a vida de Jesus, o começo da igreja e cartas cheias de ensinamentos pra quem quer viver seguindo a Deus."},{"pergunta":"Qual desses é um dos quatro Evangelhos?","alternativas":["Gênesis","Salmos","João","Rute"],"correta":2,"explicacao":"É o livro de João! Mateus, Marcos, Lucas e João são os quatro Evangelhos - cada um conta a história de Jesus com o seu próprio jeito."}]'
WHERE origem = 'kadosys' AND tipo = 'quiz' AND titulo = 'Quiz: Livros da Bíblia';

UPDATE kids_conteudos SET quiz_perguntas = '[{"pergunta":"O que Jesus transformou água em, nas bodas de Caná?","alternativas":["Suco","Vinho","Leite","Mel"],"correta":1,"explicacao":"Jesus transformou água em vinho! Foi o primeiro milagre dele, feito numa festa de casamento, mostrando que ele se importa até com os detalhes da nossa alegria."},{"pergunta":"Quantos pães Jesus usou para alimentar a multidão?","alternativas":["2","5","10","20"],"correta":1,"explicacao":"Foram só 5 pães (e 2 peixinhos)! Jesus multiplicou essa pequena oferta de um menino e alimentou milhares de pessoas. Com Deus, o pouco pode virar muito."},{"pergunta":"Sobre o que Jesus andou, para mostrar seu poder?","alternativas":["Fogo","Nuvens","Água","Areia"],"correta":2,"explicacao":"Jesus andou sobre a água do mar! Isso mostrou aos discípulos que ele tem poder sobre a natureza - e que podemos confiar nele mesmo nas tempestades da vida."}]'
WHERE origem = 'kadosys' AND tipo = 'quiz' AND titulo = 'Quiz: Milagres de Jesus';

UPDATE kids_conteudos SET quiz_perguntas = '[{"pergunta":"Quem construiu uma arca para salvar sua família e os animais?","alternativas":["Noé","Abraão","Moisés","Davi"],"correta":0,"explicacao":"Foi Noé! Ele confiou em Deus e obedeceu, mesmo quando ninguém mais acreditava que ia chover. Sua obediência salvou sua família."},{"pergunta":"Quem enfrentou o gigante Golias com uma funda?","alternativas":["Sansão","Davi","Josué","Gideão"],"correta":1,"explicacao":"Foi Davi! Ele não confiava só na sua força, mas no poder de Deus - por isso não teve medo de enfrentar um gigante."},{"pergunta":"Quem foi jogado na cova dos leões e não se machucou?","alternativas":["Daniel","José","Jonas","Elias"],"correta":0,"explicacao":"Foi Daniel! Ele continuou orando a Deus mesmo sendo proibido, e Deus fechou a boca dos leões para protegê-lo. Deus cuida de quem é fiel a ele."},{"pergunta":"Quem liderou o povo de Israel para fora do Egito?","alternativas":["Josué","Moisés","Abraão","Davi"],"correta":1,"explicacao":"Foi Moisés! Deus o escolheu para libertar o povo que vivia escravo no Egito e guiá-lo até a terra prometida."}]'
WHERE origem = 'kadosys' AND tipo = 'quiz' AND titulo = 'Quiz: Heróis do Velho Testamento';

UPDATE kids_conteudos SET quiz_perguntas = '[{"pergunta":"Na parábola do Bom Samaritano, quem ajudou o homem ferido?","alternativas":["Um sacerdote","Um samaritano","Um levita","Um soldado"],"correta":1,"explicacao":"Foi o samaritano! Mesmo sendo de um povo mal visto na época, ele parou para cuidar de um estranho ferido. Jesus ensinou que amar o próximo é cuidar de quem precisa, não importa quem seja."},{"pergunta":"Na parábola do filho pródigo, o que o pai fez quando o filho voltou?","alternativas":["Ficou bravo","Não deixou entrar","Correu para abraçá-lo","Mandou ele embora"],"correta":2,"explicacao":"O pai correu para abraçá-lo com alegria! Essa história mostra como Deus nos recebe de braços abertos sempre que voltamos para ele, não importa o que tenha acontecido."},{"pergunta":"Na parábola da ovelha perdida, quantas ovelhas o pastor tinha ao todo?","alternativas":["10","50","100","1000"],"correta":2,"explicacao":"Eram 100 ovelhas! O pastor deixou as outras 99 para ir buscar só uma que se perdeu, mostrando que cada pessoa é muito importante para Deus."},{"pergunta":"O que a semente de mostarda representa na parábola de Jesus?","alternativas":["O Reino de Deus crescendo","Uma árvore grande","Um pássaro","Uma flor"],"correta":0,"explicacao":"Representa o Reino de Deus! Ele começa pequeno, como uma sementinha, mas cresce cada vez mais - assim como a fé pode crescer dentro de nós."}]'
WHERE origem = 'kadosys' AND tipo = 'quiz' AND titulo = 'Quiz: Parábolas de Jesus';

UPDATE kids_conteudos SET quiz_perguntas = '[{"pergunta":"Qual discípulo caminhou sobre a água com Jesus?","alternativas":["João","Tiago","Pedro","André"],"correta":2,"explicacao":"Foi Pedro! Ele deu alguns passos sobre a água olhando para Jesus, mas começou a afundar quando teve medo. Jesus o segurou - ele sempre estende a mão pra nós."},{"pergunta":"Qual discípulo traiu Jesus?","alternativas":["Tomé","Judas","Filipe","Mateus"],"correta":1,"explicacao":"Foi Judas Iscariotes. Ele entregou Jesus por dinheiro, uma escolha muito triste. A história de Judas nos lembra como é importante ser fiel de verdade."},{"pergunta":"Qual discípulo duvidou da ressurreição até ver Jesus com seus próprios olhos?","alternativas":["Tomé","Pedro","João","Bartolomeu"],"correta":0,"explicacao":"Foi Tomé! Depois de ver e tocar em Jesus ressuscitado, ele finalmente creu. Jesus disse que é ainda mais especial crer mesmo sem ver."},{"pergunta":"Qual era a profissão de Mateus antes de seguir Jesus?","alternativas":["Pescador","Cobrador de impostos","Médico","Carpinteiro"],"correta":1,"explicacao":"Mateus cobrava impostos, um trabalho que muita gente não gostava. Mesmo assim, Jesus o chamou para ser discípulo - Deus escolhe qualquer pessoa que queira segui-lo."}]'
WHERE origem = 'kadosys' AND tipo = 'quiz' AND titulo = 'Quiz: Os 12 Discípulos';

UPDATE kids_conteudos SET quiz_perguntas = '[{"pergunta":"Em que dia Deus criou o sol, a lua e as estrelas?","alternativas":["Dia 2","Dia 3","Dia 4","Dia 5"],"correta":2,"explicacao":"Foi no quarto dia! Deus organizou tudo com cuidado e ordem, um passo de cada vez, para que o mundo funcionasse direitinho."},{"pergunta":"Em que dia Deus descansou?","alternativas":["Dia 5","Dia 6","Dia 7","Dia 1"],"correta":2,"explicacao":"No sétimo dia! Deus descansou depois de criar tudo, nos ensinando que descansar também é importante em nossa semana."},{"pergunta":"O que Deus criou primeiro?","alternativas":["Os animais","A luz","O homem","As plantas"],"correta":1,"explicacao":"Foi a luz! No primeiro dia, Deus disse \\"haja luz\\" e a escuridão deu lugar à claridade - o começo de tudo o que ele ainda ia criar."},{"pergunta":"De que Deus formou o primeiro homem?","alternativas":["Água","Pó da terra","Fogo","Madeira"],"correta":1,"explicacao":"Do pó da terra! Deus o formou com as próprias mãos e soprou nele o fôlego de vida - cada pessoa é uma criação especial e única de Deus."}]'
WHERE origem = 'kadosys' AND tipo = 'quiz' AND titulo = 'Quiz: A Criação do Mundo';

UPDATE kids_conteudos SET quiz_perguntas = '[{"pergunta":"Quantos frutos do Espírito são citados em Gálatas 5?","alternativas":["5","7","9","12"],"correta":2,"explicacao":"São 9 frutos: amor, alegria, paz, paciência, benignidade, bondade, fidelidade, mansidão e domínio próprio. Eles crescem em nós quando vivemos perto de Deus."},{"pergunta":"Qual destes é um fruto do Espírito?","alternativas":["Inveja","Paciência","Orgulho","Preguiça"],"correta":1,"explicacao":"É a paciência! Ela nos ajuda a esperar e a lidar bem com as dificuldades do dia a dia, confiando que Deus está no controle."},{"pergunta":"Em qual livro da Bíblia encontramos a lista do Fruto do Espírito?","alternativas":["Romanos","Gálatas","Salmos","Atos"],"correta":1,"explicacao":"É em Gálatas, capítulo 5! O apóstolo Paulo escreveu essa carta para ensinar como viver guiado pelo Espírito Santo."},{"pergunta":"Além do amor e da alegria, qual outro fruto começa com a letra P?","alternativas":["Fé","Paz","Bondade","Mansidão"],"correta":1,"explicacao":"É a paz! Deus quer que tenhamos um coração tranquilo, sem brigas nem preocupação demais, confiando nele."}]'
WHERE origem = 'kadosys' AND tipo = 'quiz' AND titulo = 'Quiz: Frutos do Espírito';

UPDATE kids_conteudos SET quiz_perguntas = '[{"pergunta":"O que aconteceu no dia de Pentecostes?","alternativas":["Choveu","O Espírito Santo desceu sobre os discípulos","Houve um terremoto","Jesus subiu ao céu"],"correta":1,"explicacao":"O Espírito Santo desceu sobre os discípulos! Isso deu coragem e força para eles contarem a todos as boas notícias sobre Jesus, e assim a igreja começou."},{"pergunta":"Quem era Saulo antes de se tornar o apóstolo Paulo?","alternativas":["Um pescador","Um perseguidor dos cristãos","Um rei","Um sacerdote"],"correta":1,"explicacao":"Ele perseguia os cristãos! Mas depois de encontrar Jesus numa luz forte no caminho, Saulo mudou completamente e virou Paulo, um dos maiores anunciadores da fé."},{"pergunta":"O que os primeiros cristãos faziam juntos, segundo Atos 2?","alternativas":["Brigavam por comida","Partilhavam tudo o que tinham","Escondiam suas coisas","Viviam sozinhos"],"correta":1,"explicacao":"Eles partilhavam tudo o que tinham! Cuidavam uns dos outros com generosidade, um exemplo bonito de amor entre irmãos na fé."},{"pergunta":"Quem foi o primeiro mártir cristão, apedrejado por sua fé?","alternativas":["Pedro","Estêvão","Filipe","Tiago"],"correta":1,"explicacao":"Foi Estêvão! Mesmo sendo apedrejado, ele perdoou quem fez aquilo com ele, seguindo o exemplo de amor e perdão que Jesus ensinou."}]'
WHERE origem = 'kadosys' AND tipo = 'quiz' AND titulo = 'Quiz: A Igreja Primitiva';

UPDATE kids_conteudos SET quiz_perguntas = '[{"pergunta":"Segundo Provérbios, o que é o começo da sabedoria?","alternativas":["Estudar muito","O temor do Senhor","Ser rico","Ter muitos amigos"],"correta":1,"explicacao":"É o temor do Senhor - ou seja, respeitar e amar a Deus de verdade. Quando colocamos Deus em primeiro lugar, aprendemos a viver com sabedoria."},{"pergunta":"Provérbios ensina que devemos confiar no Senhor de...","alternativas":["Todo o coração","Vez em quando","Apenas nos domingos","Só quando precisamos"],"correta":0,"explicacao":"De todo o coração! Provérbios 3:5 ensina para confiarmos em Deus sempre, sem depender só do nosso próprio entendimento."},{"pergunta":"Quem escreveu a maior parte do livro de Provérbios?","alternativas":["Davi","Salomão","Moisés","Paulo"],"correta":1,"explicacao":"Foi o rei Salomão! Deus deu a ele uma sabedoria muito grande, e Salomão escreveu esses conselhos para ajudar as pessoas a viverem melhor."},{"pergunta":"O que Provérbios diz sobre a resposta mansa?","alternativas":["Que afasta o furor","Que não serve pra nada","Que é sinal de fraqueza","Que ninguém entende"],"correta":0,"explicacao":"Que ela afasta o furor! Responder com calma, mesmo quando alguém está bravo, ajuda a acalmar a situação em vez de piorar a briga."}]'
WHERE origem = 'kadosys' AND tipo = 'quiz' AND titulo = 'Quiz: Provérbios e Sabedoria';

UPDATE kids_conteudos SET quiz_perguntas = '[{"pergunta":"Em que cidade Jesus nasceu?","alternativas":["Nazaré","Belém","Jerusalém","Jericó"],"correta":1,"explicacao":"Foi em Belém! Isso já tinha sido anunciado por profetas centenas de anos antes - Deus cumpre suas promessas no tempo certo."},{"pergunta":"O que os pastores viram no céu anunciando o nascimento de Jesus?","alternativas":["Um cometa","Uma tempestade","Anjos","Um arco-íris"],"correta":2,"explicacao":"Eles viram anjos! Os anjos anunciaram a boa notícia do nascimento de Jesus primeiro para pastores simples, mostrando que essa alegria é para todos."},{"pergunta":"O que comemoramos na Páscoa cristã?","alternativas":["O nascimento de Jesus","A ressurreição de Jesus","O batismo de Jesus","A subida ao céu"],"correta":1,"explicacao":"A ressurreição de Jesus! Ele venceu a morte e está vivo, e essa é a maior alegria da fé cristã."},{"pergunta":"Quantos dias depois de morrer Jesus ressuscitou?","alternativas":["1","2","3","7"],"correta":2,"explicacao":"No terceiro dia! Assim como Jesus prometeu antes de morrer, ele ressuscitou exatamente como havia dito - podemos confiar em cada palavra dele."}]'
WHERE origem = 'kadosys' AND tipo = 'quiz' AND titulo = 'Quiz: Natal e Páscoa';
